
[env]
TERM = "xterm-256color"

[window]
option_as_alt = "OnlyLeft"
padding.x = 16
padding.y = 12

decorations = "Buttonless"

opacity = 1
blur = true

[cursor]
style = { shape = "Underline", blinking = "Never" }
thickness = 0.35

[mouse]
hide_when_typing = false


[font]
size = 17

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"


[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"


[font.offset]
x = 0

[keyboard]
bindings = [
    { key = "v", mods = "Command", action = "Paste" },
    { key = "м", mods = "Command", action = "Paste" },
    { key = "c", mods = "Command", action = "Copy" },
    { key = "с", mods = "Command", action = "Copy" },
    { key = "M", mods = "Control", action = "None" },
    { key = "1", mods = "Control", chars = "\u001b[27;5;49~" },
    { key = "2", mods = "Control", chars = "\u001b[27;5;50~" },
    { key = "3", mods = "Control", chars = "\u001b[27;5;51~" },
    { key = "4", mods = "Control", chars = "\u001b[27;5;52~" },
    { key = "5", mods = "Control", chars = "\u001b[27;5;53~" },
    { key = "6", mods = "Control", chars = "\u001b[27;5;54~" },
    { key = "7", mods = "Control", chars = "\u001b[27;5;55~" },
    { key = "8", mods = "Control", chars = "\u001b[27;5;56~" },
    { key = "9", mods = "Control", chars = "\u001b[27;5;57~" },
]
